### ISSUE TITLE
SEGFAULT when mod.TableIter() is not iterated over directly

### ISSUE THREAD

**Issue by cpg1111** [iovisor/gobpf#107]
Say I have the code

```
func example(mod *bcc.Module) {
    for entry := range mod.TableIter() {
        for k, v := range entry {
            fmt.Println(k, v)
        }
    }
}
```

that code works fine, but now say I want to set the return value to a variable and pass it to another function like so

```
func print(c chan map[string]interface{}) {
    for entry := range c {
        for k, v := range entry {
            fmt.Println(k, v)
        }
    }
}

func example(mod *bcc.Module) {
    iter := mod.TableIter()
    print(iter)
}
```

I get a SEGFAULT, which here's my actual stacktrace

```
unexpected fault address 0x13660
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x13660 pc=0x4441fb]

goroutine 7 [running]:
runtime.throw(0x618121, 0x5)
        /usr/lib/go-1.8/src/runtime/panic.go:596 +0x95 fp=0xc420027e10 sp=0xc420027df0
runtime.sigpanic()
        /usr/lib/go-1.8/src/runtime/signal_unix.go:297 +0x28c fp=0xc420027e60 sp=0xc420027e10
runtime.findnull(0x13660, 0x5a4af0)
        /usr/lib/go-1.8/src/runtime/string.go:392 +0x1b fp=0xc420027e68 sp=0xc420027e60
runtime.gostring(0x13660, 0x0, 0x0)
        /usr/lib/go-1.8/src/runtime/string.go:285 +0x2f fp=0xc420027ec0 sp=0xc420027e68
github.com/cpg1111/pprof-ebpf/vendor/github.com/iovisor/gobpf/bcc._Cfunc_GoString(0x13660, 0x0, 0x13660)
        github.com/cpg1111/pprof-ebpf/vendor/github.com/iovisor/gobpf/bcc/_obj/_cgo_gotypes.go:285 +0x2b fp=0xc420027ee8 sp=0xc420027ec0
github.com/cpg1111/pprof-ebpf/vendor/github.com/iovisor/gobpf/bcc.(*Module).TableDesc(0xc42000c460, 0x0, 0xc420027fc8)
        /home/vagrant/go/src/github.com/cpg1111/pprof-ebpf/vendor/github.com/iovisor/gobpf/bcc/module.go:338 +0x5e fp=0xc420027f90 sp=0xc420027ee8
github.com/cpg1111/pprof-ebpf/vendor/github.com/iovisor/gobpf/bcc.(*Module).TableIter.func1(0xc42000c460, 0xc420056540)
        /home/vagrant/go/src/github.com/cpg1111/pprof-ebpf/vendor/github.com/iovisor/gobpf/bcc/module.go:353 +0x5b fp=0xc420027fd0 sp=0xc420027f90
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420027fd8 sp=0xc420027fd0
created by github.com/cpg1111/pprof-ebpf/vendor/github.com/iovisor/gobpf/bcc.(*Module).TableIter
        /home/vagrant/go/src/github.com/cpg1111/pprof-ebpf/vendor/github.com/iovisor/gobpf/bcc/module.go:356 +0x67

goroutine 1 [chan receive]:
github.com/cpg1111/pprof-ebpf/pkg/output.(*Parser).ParseEntry(0xc420099c10, 0x0, 0x0)
        /home/vagrant/go/src/github.com/cpg1111/pprof-ebpf/pkg/output/parse.go:18 +0x67
github.com/cpg1111/pprof-ebpf/cmd.glob..func1(0x914b00, 0x945140, 0x0, 0x0)
        /home/vagrant/go/src/github.com/cpg1111/pprof-ebpf/cmd/cpuprofile.go:101 +0xf4
github.com/cpg1111/pprof-ebpf/vendor/github.com/spf13/cobra.(*Command).execute(0x914b00, 0x945140, 0x0, 0x0, 0x914b00, 0x945140)
        /home/vagrant/go/src/github.com/cpg1111/pprof-ebpf/vendor/github.com/spf13/cobra/command.go:702 +0x2bd
github.com/cpg1111/pprof-ebpf/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42008e000, 0xc420049f10, 0x1, 0xc42008e000)
        /home/vagrant/go/src/github.com/cpg1111/pprof-ebpf/vendor/github.com/spf13/cobra/command.go:783 +0x349
github.com/cpg1111/pprof-ebpf/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42008e000, 0xc420049f08, 0x1)
        /home/vagrant/go/src/github.com/cpg1111/pprof-ebpf/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/cpg1111/pprof-ebpf/cmd.Execute()
        /home/vagrant/go/src/github.com/cpg1111/pprof-ebpf/cmd/root.go:23 +0x14f
main.main()
        /home/vagrant/go/src/github.com/cpg1111/pprof-ebpf/main.go:11 +0x9b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

goroutine 6 [chan receive]:
github.com/cpg1111/pprof-ebpf/vendor/github.com/iovisor/gobpf/bcc.compile()
        /home/vagrant/go/src/github.com/cpg1111/pprof-ebpf/vendor/github.com/iovisor/gobpf/bcc/module.go:110 +0x74
created by github.com/cpg1111/pprof-ebpf/vendor/github.com/iovisor/gobpf/bcc.bpfInit
        /home/vagrant/go/src/github.com/cpg1111/pprof-ebpf/vendor/github.com/iovisor/gobpf/bcc/module.go:68 +0x15f
```

I'm using Go 1.8 as the stacktraces indicate, HEAD for gobpf and bcc v0.5.0 on a 4.10.X kernel.

I've looked at the `*bcc.Module.TableIter()` source code and nothing pops out to me as the issue in the Go parts of the code.  I'm currently reading through the bcc c code to try to find something, but my C / C++ isn't as strong as my Go, so I'd be happy to submit a patch if I can find the issue, but otherwise, assistance is greatly appreciated and probably needed :slightly_smiling_face: .

**Comment by cpg1111** [comment]
Nevermind, it was pilot error.  I was closing the module before reading from the channel.
